repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.3
    hooks:
    -   id: python-safety-dependencies-check
